### ISSUE TITLE
Company imports in smarkets style or smarknexus

### ISSUE THREAD

**Issue by janrito** [PyCQA/flake8-import-order#101]
Internally, we use the smarkets style, but with the addition of an import group for internal (company) pip distributed packages. Similar to what is already available for the google style, renamed appnexus.

Could we have support for `application-import-names` and `application-package-names` in either the smarkets style or a new smarknexus style? 

Happy to submit a PR if this is something people are interested.

**Comment by pgjones** [comment]
I think it should be a new style, as the Smarkets style has no concept of application-package-names (same argument for appnexus and google). I'll welcome a pull request. I'm not convinced of the name though, what about your companies name?

**Comment by janrito** [comment]
Great! PR here: https://github.com/PyCQA/flake8-import-order/pull/102

**Comment by janrito** [comment]
Thanks @pgjones!
