### ISSUE TITLE
Make case insensitivity optional

### ISSUE THREAD

**Issue by gilbsgilbs** [PyCQA/flake8-import-order#114]
Hi, 

Would it be possible to add an option to make case insensitivity optional? I really find that taking case into account just makes more sense and helps separating constants, classes and variables imports. We could add an option like `ignore-imports-case` that would default to true. I don't really want to put this logic into my projects, so it would help if it were proposed as a built-in option.

Would a contribution in this direction be accepted?

Thanks.

**Comment by pgjones** [comment]
Which style are you using? A number of the styles are case sensitive. 
Assuming the one you are using isn't, it would be preferred if you created your own [style extension](https://github.com/PyCQA/flake8-import-order#extending-styles).

**Comment by gilbsgilbs** [comment]
Hi!
I'm using `smarkets` which is a perfect fit for me, apart from the case insensitivity… Style extension is not really an option since I don't want to put import-order related code into my projects. Sure I can host the style in a separate project but that's not as good as having this built-in. And insensitive-smarket seems so natural to me.

No big deal :) .

**Comment by pgjones** [comment]
I'm a little confused as smarkets is case sensitive, in that `B` must be before `b` for [example](https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/wrong_import_order.py) (I'm guessing you meant `apart from the case *sensitivity*`). That said I think the best option is a specific style rather than an configuration addition, so sadly I will close as wontfix.

**Comment by gilbsgilbs** [comment]
What I would expect:
```
from X import BEAVER, ZOO, Ant, Parrot, chicken, horse
```
Constants, classes and variable imports are separated. It's cleaner.

What is currently expected:
```
from X import Ant, BEAVER, chicken, horse, Parrot, ZOO
```
It's messier I think. It mixes up things from different kinds.

I'm unsure if the same behavior is expected for module imports. I only use lowercase modules names (and everybody should be doing this, no?)

**Comment by pgjones** [comment]
I see, this would definitely require a new style, but is doable as long as it is `UPPER, Capitalised, lower` ordering (with each individually alphabetical) as this plugin cannot determine anything but the literal string name of the import.

**Comment by sigmavirus24** [comment]
> I'm unsure if the same behavior is expected for module imports (but I think so). I only use lowercase modules names (and everybody should be doing this too, isn't it?)

Many people still use Python 2.7 in which there are modules named `Queue`, `ConfigParser`, and a few other mixed case names. How should those be sorted?

**Comment by untitaker** [comment]
@sigmavirus24 what about a whitelist for stdlib modules?

**Comment by gilbsgilbs** [comment]
@sigmavirus24 I think I would expect them to be sorted first too.
```python
import MUPPERCASE
import ConfigParser
import MModule
import Queue
import functools
from animals import BEAVER, ZEBRA, Ant, Parrot, chicken, horse
```

**Comment by sigmavirus24** [comment]
Either way, the smarkets style isn't really up for debate here. As @pgjones mentioned, this should be a new style that you can fork from the smarkets style and publish to PyPI.
