### ISSUE TITLE
I202 flags multiline imports 

### ISSUE THREAD

**Issue by andrew-regan** [PyCQA/flake8-import-order#116]
I have several import statements that wrap lines due to line length restrictions. The recent changes for I202 flag these as in violation.

Examples:
```
from foo import bar, baz, \
    bee
```

```
from foo import (bar, baz, 
    bee)
```

I also haven't found a way to ignore these by adding `# noqa: I202` because that looks to also cause I202 to be raised.

**Comment by andrew-regan** [comment]
@pgjones FYI

**Comment by pgjones** [comment]
I think the current master branch should fix this, could you try it can confirm?

**Comment by alex** [comment]
@pgjones I can confirm that it fixes the issue for me. Thanks!

**Comment by andrew-regan** [comment]
@pgjones confirmed and thanks for the quick fix!

**Comment by pgjones** [comment]
Thanks, 0.14.1 released.
