### ISSUE TITLE
Ignore comment lines from I202?

### ISSUE THREAD

**Issue by clokep** [PyCQA/flake8-import-order#123]
Not sure if this is a bug really, but there's a couple of places I have code like:

```python
import os
# Need to import this for xyz.
import sys

...
```

This ends up with an error:
```bash
$ flake8 --import-order-style appnexus temp.py
temp.py:3:1: I202 Additional newline in a section of imports.
```

Comments are explicit though, so maybe they should be ignored in the [spacing check](https://github.com/PyCQA/flake8-import-order/blob/e2e6e3ced50d6dc23b7a013a7ee124e4db3d8166/flake8_import_order/styles.py#L73-L78)?

What do you think?

**Comment by nsoranzo** [comment]
:+1:

**Comment by pgjones** [comment]
Can you think of other things that would be best ignored from a spacing viewpoint?

**Comment by clokep** [comment]
I think I ran into a similar issue when doing:

```python
import re
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO  # noqa: F401
import sys
```

This results in:

```
flake8 --import-order-style appnexus temp.py
temp.py:6:1: I202 Additional newline in a section of imports.
```

The second `StringIO` import is marked as "ununused", but that's fine. The `sys` import, however, was marked as having an additional newline above it when it didn't. This might also just be a weird case though since `cStringIO` and `StringIO` aren't the same module name and it's vague what order to put these in. 😄 

Not sure if that's the same root cause or not though.

**Comment by nsoranzo** [comment]
Also, the I202 error is reported for imports where I've added `# noqa: I100`, for example in a script which imports from another file in the same directory (for which I cannot use `from . import foo` because that's a script not a module):
```
import requests
from six.moves.urllib.parse import urlencode

import foo  # noqa: I100
```

**Comment by pgjones** [comment]
I think [this commit](https://github.com/pgjones/flake8-import-order/commit/87a611f0e24d2ccf0308944128ea47bd1eede2b8) is likely to fix all the edge cases related to what is or not a newline this. Could you try it and confirm?

Regarding the `import foo  # noqa: I100` question, I think this is the correct error reporting as there is an additional newline, and this plugin now respects the conditional `noqa`. I think you should change to `import foo  # noqa: I100, I202`.

**Comment by clokep** [comment]
@pgjones I can confirm that this fixes the case for me (and doesn't cause any additional flake8 warnings in my project).

**Comment by nsoranzo** [comment]
Works for me!

>  I think you should change to `import foo # noqa: I100, I202`.

Fair enough.

**Comment by pgjones** [comment]
Thanks, fixed in master.

**Comment by clokep** [comment]
Awesome! Thanks for fixing this. 👍

**Comment by nsoranzo** [comment]
Thanks @pgjones, are you planning a release containing the fix?

**Comment by pgjones** [comment]
Yep, I wish to resolve the current pull requests first.

**Comment by pgjones** [comment]
Released now.
