### ISSUE TITLE
application-package-names doesn't work with namespaced packages

### ISSUE THREAD

**Issue by gilbsgilbs** [PyCQA/flake8-import-order#124]
Hi,

The `application-package-names` doesn't seem to work properly with namespaced packages.

E.g.
```
# flake8-import-order will consider this as a third-party package, and disallow newlines
application-package-names = mynamespace.myproject
```

This is probably because the `root_package_name` function considers `mynamespace` to be the root package name.

https://github.com/PyCQA/flake8-import-order/blob/b563bc958d37b017cb9c79ab85121299bd459137/flake8_import_order/__init__.py#L82

**Comment by gilbsgilbs** [comment]
Duplicate of https://github.com/PyCQA/flake8-import-order/issues/111 . Sorry.

**Comment by pgjones** [comment]
Thanks, I think solving #111 will solve this.

**Comment by pgjones** [comment]
Could you check to see if #126 fixes this?
