### ISSUE TITLE
Improve coverage setup in repo

### ISSUE THREAD

**Issue by taion** [PyCQA/flake8-import-order#129]
There are a couple of odd things with the coverage configuration here:

- The `tests/` directory is included under coverage sources, so coverage reports coverage on the tests files. This is quite odd; coverage on the test modules themselves is seldom interesting, and in general people only want to see coverage on the source.
- The coverage status doesn't feed into any integration-style reports. I'm not sure what the requirements around coverage are for PRs, but given that all the work in setting up coverage is done, it's pretty easy to enable e.g. Codecov to report coverage changes in PRs.

Also, at this point it'd probably be a bit cleaner to use pytest-cov than to invoke coverage directly.

I'd be happy to open a PR to address these if these are legitimate things worth addressing.

**Comment by pgjones** [comment]
I personally find the coverage metric interesting but not something to fixate on, so I'm marginal on the codecov integration. I'd happily accept a PR that improves the coverage usage though.

**Comment by taion** [comment]
Sure – the biggest benefit I get from using Codecov is that Codecov shows me the coverage diff from patches, so I can verify that new code added in PRs does have appropriate test coverage. See e.g. the check results for https://github.com/4Catalyzer/flask-resty/pull/129 (not super interesting because that repo is at 100% coverage and so is the patch... but then again this repo is too).

The coverage diff there is something I'm not aware that I can get easily out of using coverage tools directly, and I've found it useful in the past. Though having to tweak coverage thresholds to not make PRs undesirably go red on CI isn't fun, so I can sympathize.
