### ISSUE TITLE
I202 errors for multiline imports

### ISSUE THREAD

**Issue by philtay** [PyCQA/flake8-import-order#135]
The following snippet triggers an I202 error:

```python
from .foo import (
    bar,
    baz,
)

from .zoo import (
    mux,
    mox,
)
```

I think that a blank line should be allowed when a single import spans multiple lines.

**Comment by pgjones** [comment]
Isn't the `I202` due to the newline between these two imports in this case? If so (depending on the style you are using) it is likely correct.

**Comment by philtay** [comment]
Yes, it's the newline between the imports. Look how ugly it is without:

```python
from .foo import (
    bar,
    baz,
)
from .zoo import (
    mux,
    mox,
)
from .moo import (
    yux,
    yox,
)
```
I think that multiline imports should be allowed to be separated by a newline.

**Comment by pgjones** [comment]
Fair enough, however all the styles in this package expect the newlines to be absent. I think your best bet is to write your own [style](https://github.com/PyCQA/flake8-import-order#extending-styles) with the newlines expected or simply ignore the `I202` error.
