### ISSUE TITLE
Make case-sensitivity optional

### ISSUE THREAD

**Issue by immerrr** [PyCQA/flake8-import-order#146]
Hi and thank you for a nice package.

I have a minor problem with it. I'm using [isort](https://pypi.python.org/pypi/isort) to format imports automatically and it ends up sorting `from ... import ...` imports in case-sensitive manner, ie. `from ... import Baz, bar` which is then reported by flake8 as incorrect. It just so happens that isort doesn't have an option to switch case-sensitivity either, so I'm kinda stuck.

**Comment by pgjones** [comment]
The styles have defined case sensitivity though, which doesn't help here. Do you have any thoughts on how to make #99 work?

**Comment by immerrr** [comment]
I don't think I have experience hacking flake8, sorry. 

Regarding case-sensitivity, I'm not sure it's harmful to add a configuration parameter that by default produces output as defined by certain "styles" and can be configured to do a slightly different thing. If you really care about styles being set in stone from the dawn of time you could add a family of `{style}_cs` styles enabling case sensitivity [MySQL style](https://dev.mysql.com/doc/refman/5.7/en/charset-mysql.html), but not even touching the already existing options.

**Comment by immerrr** [comment]
While I was preparing a case for isort project, I couldn't but notice that google style guide [doesn't explicitly touch case sensitivity on imports from the same module](http://google.github.io/styleguide/pyguide.html?showone=Imports_formatting#Imports_formatting).   It only mentions being case-insensitive w.r.t different import statements, because multiple imports from the same module are forbidden altogether.

**Comment by pgjones** [comment]
There is [`flake8-isort`](https://github.com/gforcada/flake8-isort) that might solve this exact issue.

**Comment by sigmavirus24** [comment]
It might, but it's also GPL v2 which is often a problem for people
