### ISSUE TITLE
Unable to disable warnings via tox.ini

### ISSUE THREAD

**Issue by Integralist** [PyCQA/flake8-import-order#164]
I've tried the following, but my vim linter still seems to pick up the `I202` error.

Is tox supported or have I just mis-configured things?

Otherwise love this plugin.

Thanks!

```
[flake8]
ignore = E261,E265,E402
# http://pep8.readthedocs.org/en/latest/intro.html#error-codes

[flake8-import-order]
ignore = I202
# https://github.com/PyCQA/flake8-import-order#warnings
```

**Comment by Integralist** [comment]
Also, just as a side comment...

```py
# standard library modules

import re
from datetime import datetime, timedelta
from functools import partial

# external modules

from bf_api_gateway.tornado.rig import api_gateway

from bf_auth.utility import build_endpoint, configure_fetch, instr, require_auth

from bf_rig import settings
```

For some reason the external modules (which are identified as 'Third Party' require line breaks, but the Stdlib module imports don't?

Is that by design?

**Comment by sigmavirus24** [comment]
> have I just mis-configured things?

Yes. Your config should be

```ini
[flake8]
ignore = E261,E265,E402,I202
# http://pep8.readthedocs.org/en/latest/intro.html#error-codes
# https://github.com/PyCQA/flake8-import-order#warnings
```

**Comment by Integralist** [comment]
I did try that and it didn't work, but trying it again this morning it _does_ work 🤦‍♂️ 

Thanks for confirming though 👍
