### ISSUE TITLE
Not detecting local imports

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/flake8-import-order#170]
I keep getting I100 and I202 because it detects imports as third-party, when they are local modules in the application. e.g.
`Additional newline in a group of imports. 'from constants import MARGIN' is identified as Third Party..`

Shouldn't it be able to see that these modules are local (i.e. they are in the same directory as the file doing the importing)?

**Comment by pgjones** [comment]
Hi @Dreamsorcerer, this plugin cannot detect which packages are local, instead you must inform it via the [configuration `application-import-names`](https://github.com/PyCQA/flake8-import-order#configuration),
