### ISSUE TITLE
Apply the ordering rules to __all__

### ISSUE THREAD

**Issue by tlocke** [PyCQA/flake8-import-order#180]
Hi, I'm a great fan of flake8-import-order, thanks for working on it :-). My suggestion is to apply the same ordering rules to the [\_\_all__](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) module attribute. Would that be a good idea?

**Comment by sigmavirus24** [comment]
In #163 we discuss that this project is vaguely under a feature-freeze. I don't have opinions on whether `__all__` should be ordered or not but I'm not sure it'll be implemented by this project either way

**Comment by tlocke** [comment]
Okay, I'll close this issue then. Btw, I wrote https://github.com/tlocke/flake8-alphabetize to do the sorting of `__all__` as well as sorting imports.
