### ISSUE TITLE
Impossible requirements with capitalised import

### ISSUE THREAD

**Issue by calvingiles** [PyCQA/flake8-import-order#49]
flake8: `access.py:5:1: I101 Imported names are in the wrong order. Should be connection, IntegrityError, transaction`

line 5 of access.py: `from django.db import connection, IntegrityError, transaction`

Resolved with:

```
from django.db import IntegrityError
from django.db import connection, transaction
```

**Comment by public** [comment]
Can't reproduce. What version are you using?

**Comment by untitaker** [comment]
I think this is related to #47.

**Comment by pgjones** [comment]
I can reproduce, will fix.
