### ISSUE TITLE
Possible to automatically determine application import names?

### ISSUE THREAD

**Issue by jonparrott** [PyCQA/flake8-import-order#86]
Presently it's pretty fragile to list every application-local import name for --application-import-names. Is it possible to check for the presence of the module file in the directory to figure it out?

**Comment by pgjones** [comment]
This is a good idea, however I'm not sure if it is possible. I had plans to investigate this and automatic stdlib listing.

**Comment by jonparrott** [comment]
Let me know what I can do to help, currently I'm approximating this with `os.listdir` and passing folder names and the basename of .py files. Works well enough for my case, but definitely not a robust solution.

**Comment by sigmavirus24** [comment]
@jonparrott I suspect you have different project layouts than most. Can you provide an example layout that you're trying to solve for?

**Comment by jonparrott** [comment]
We most certainly do. https://github.com/GoogleCloudPlatform/python-docs-samples

It's essentially a large collection of independent (small) applications.

**Comment by public** [comment]
"application names" aren't really a concept that exists within the import system which is why it works how it does right now. I also wrote it to explicitly not have to check sys.path or anything at run time.

Is there anything in particular that is problematic to you about externally generating static config prior to running flake8?

**Comment by jonparrott** [comment]
> Is there anything in particular that is problematic to you about externally generating static config prior to running flake8?

Eh, it's not problematic (we have nox do it [here](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/nox.py#L254)) it would just be nice to have a little less code. :)

> "application names" aren't really a concept that exists within the import system which is why it works how it does right now.

Understood.

> I also wrote it to explicitly not have to check sys.path or anything at run time.

That's fair, the closer it is to static analysis the better.

**Comment by pgjones** [comment]
Given @public comments on the explicit aims of the project and a lack of ideas of how to achieve this whilst meeting those aims I think it is best to close.
