### ISSUE TITLE
Compat for modules like concurrent.futures which are not bulid-in in python2

### ISSUE THREAD

**Issue by triostones** [PyCQA/flake8-import-order#89]
Hi!
I found `flake8-import-order` can not work well with some modules which are only built-in in python3 in python2 environment, like `concurrent.futures`. For example:
```
$ cat a.py
import concurrent.futures
import click

$ python --version
Python 2.7.10

$ flake8 a.py 
a.py:1:1: F401 'concurrent.futures' imported but unused
a.py:2:1: F401 'click' imported but unused
```
There is no `I100` warning which should show in python2.

Then I modified `a.py`:
```
$ cat a.py 
import click
import concurrent.futures

$ flake8 a.py 
a.py:1:1: F401 'click' imported but unused
a.py:2:1: F401 'concurrent.futures' imported but unused
a.py:2:1: I100 Import statements are in the wrong order.import concurrent.futures should be before import click
```
There is an `I100` warning which should not show in this import order.

I think it should be more flexible in python2 for these modules like `concurrent.futures`.

Thanks for your patience and sorry for my poor English.

**Comment by pgjones** [comment]
Hello, you are right this is a limitation of this linter. This limitation is intentional, although it should be mentioned in the README, as a fix is not obvious and is likely to result in a breaking change for users. That said if you have a suggested fix please open a pull request :).

**Comment by pgjones** [comment]
I've added a limitation for this in the README, see 7dc79c256cf0ac68e83829834a4493ed1cb72b3c.
