### ISSUE TITLE
Possible bug in smarkets style checking

### ISSUE THREAD

**Issue by marpetr** [PyCQA/flake8-import-order#91]
I have a file with the following group of imports:

```python
import datetime
import dateutil.parser
import logging


datetime
dateutil.parser
logging
```

Import order looks right, but flake8 complains about it:
```
$ flake8 foo.py
foo.py:3:1: I100 Import statements are in the wrong order.import logging should be before import dateutil.parser
```

Rearranging imports in the following order satisfies flake8:
```python
import datetime
import logging
import dateutil.parser
```

Is this intended by design? I couldn't find the precise definition of *smarkets* import style, hence can't tell where is the problem.

**Comment by sigmavirus24** [comment]
Most import orderings want stdlib imports grouped before non-stdlib imports. So `datetime` and `logging` would come prior to `dateutil` as that's a third-party. `smarkets` is defined in [Configuration](https://github.com/PyCQA/flake8-import-order#configuration) with an [example](https://github.com/PyCQA/flake8-import-order/blob/master/tests/test_cases/complete_smarkets.py).

**Comment by marpetr** [comment]
My apologies. That is perfectly correct behavior.
